// Edit Mode end to end: create an Edit Mode career, edit a player, move one, script an AI match and check the result.
// node scripts/qa/edit-ui.mjs <out-dir>
import { chromium } from 'playwright'
import fs from 'node:fs'
const OUT = process.argv[2] || '/tmp/opus-edit'; fs.mkdirSync(OUT, { recursive: true })
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' })
const page = await (await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true })).newPage()
const errors = []
page.on('pageerror', (e) => errors.push(`pageerror: ${e.message}`))
page.on('console', (m) => { if (m.type() === 'error' && !/Failed to load resource|ERR_/.test(m.text())) errors.push(`console: ${m.text()}`) })
let n = 0
const shot = async (name, wait = 450) => { await page.waitForTimeout(wait); await page.screenshot({ path: `${OUT}/${String(++n).padStart(2, '0')}-${name}.png` }) }
const scroll = (y, sel = '.screen') => page.evaluate(([y, sel]) => { const s = [...document.querySelectorAll(sel)].pop(); if (s) s.scrollTop = y }, [y, sel])
await page.goto('http://localhost:5173/')
await page.getByText('New Career').first().click()
await page.waitForSelector('input[placeholder="First name"]', { timeout: 30000 })
await page.fill('input[placeholder="First name"]', 'Jo'); await page.fill('input[placeholder="Last name"]', 'Silva')
await page.getByText('Continue').first().click(); await page.getByText('Premier League').first().click(); await page.locator('.club-card').nth(1).click()
await page.getByRole('button', { name: /^Manage/ }).click()
await scroll(2000)
await page.getByText('Enable Edit Mode').click()
await shot('settings-editmode')
await page.getByText('Continue').first().click()
await shot('confirm')
await page.getByText('Start Career').first().click()
await page.waitForSelector('.continue-btn', { timeout: 90000 })
await shot('central')
// a player: edit attributes
const pid = await page.evaluate(() => { const w = window.__game.getState().world; return Object.values(w.players).filter((p) => p.clubId === w.userClubId && !p.academy).sort((a, b) => a.ovr - b.ovr)[5].id })
const before = await page.evaluate((id) => window.__game.getState().world.players[id].ovr, pid)
await page.evaluate((id) => window.__game.getState().go({ name: 'player', params: { id } }), pid)
await page.waitForTimeout(700)
await page.locator('.edit-btn').first().click()
await shot('player-editing', 700)
await page.getByText('+5 all').click(); await page.getByText('+5 all').click()
await shot('player-attrs')
await page.getByText('Apply changes').click()
await shot('player-applied', 700)
const after = await page.evaluate((id) => window.__game.getState().world.players[id].ovr, pid)
// move him to another club
await page.locator('.edit-btn').first().click()
await page.locator('.ed-card .seg button', { hasText: 'Move' }).click()
await page.fill('.ed-card input', 'Barcelona')
await page.waitForTimeout(300)
await page.locator('.ed-club').first().click()
await shot('player-move', 500)
await page.locator('.ed-card button.ed-apply', { hasText: 'Move to' }).click()
await shot('player-moved', 800)
const moved = await page.evaluate((id) => { const w = window.__game.getState().world; return w.clubs[w.players[id].clubId]?.short }, pid)
// script an AI match two days out
const fx = await page.evaluate(() => { const w = window.__game.getState().world; const f = Object.values(w.fixtures).filter((x) => !x.played && !x.userInvolved && w.competitions[x.compId]?.format === 'league' && w.competitions[x.compId]?.leagueId === w.clubs[w.userClubId].leagueId).sort((a, b) => a.date.localeCompare(b.date))[0]; return { id: f.id, date: f.date, home: w.clubs[f.home].short, away: w.clubs[f.away].short } })
await page.evaluate((id) => window.__game.getState().go({ name: 'comp', params: { id: window.__game.getState().world.fixtures[id].compId } }), fx.id)
await page.waitForTimeout(600)
await page.locator('.tab', { hasText: 'Fixtures' }).first().click()
await page.waitForTimeout(400)
await page.locator('.fixture-row', { hasText: fx.home }).first().click()
await shot('fixture-sheet', 500)
await page.locator('.ed-open').click()
await shot('script-simple', 600)
await page.locator('.sc-level').nth(4).click()
await shot('script-simple-set')
await page.locator('.sc .seg button', { hasText: 'Advanced' }).click()
await page.locator('.sc-sec button', { hasText: 'Let it play out' }).click()
await page.locator('.sc-add button', { hasText: 'Goal' }).click()
await shot('script-goal-form', 500)
await page.locator('.sc-evform .ed-apply').click()
await page.locator('.sc-add button', { hasText: 'Penalty' }).click()
await page.locator('.sc-evform .seg button', { hasText: 'Saved' }).click()
await page.locator('.sc-spot.s-TL').click()
await shot('script-pen-form', 400)
await page.locator('.sc-evform .ed-apply').click()
await page.locator('.sc-add button', { hasText: 'Red card' }).click()
await page.locator('.sc-evform .seg button').nth(1).click()
await page.locator('.sc-evform .ed-apply').click()
await scroll(0, '.sheet'); await shot('script-advanced', 500)
await scroll(600, '.sheet'); await shot('script-advanced-2')
await page.locator('.sc .ed-apply', { hasText: 'Save script' }).click()
await page.waitForTimeout(500)
const script = await page.evaluate((id) => window.__game.getState().world.scripts?.[id], fx.id)
// play past it
await page.evaluate(async (date) => {
  const mr = await import('/src/engine/world/matchRunner.ts'); const adv = await import('/src/engine/world/advance.ts')
  const G = window.__game; G.setState({ prefs: { ...G.getState().prefs, reduceMotion: true } })
  for (let i = 0; i < 12 && G.getState().world.date <= date; i++) {
    await G.getState().advance(); G.getState().closeAll()
    const w = G.getState().world; const f = adv.userFixtureOn(w, w.date)
    if (f && !f.played) { const sim = mr.createSim(w, f, true); G.getState().finishUserMatch(f.id, sim.runToEnd()); G.getState().closeAll() }
  }
}, fx.date)
const res = await page.evaluate((id) => { const w = window.__game.getState().world; const f = w.fixtures[id]; return { played: f.played, edited: f.edited, score: f.result?.score, ev: (f.result?.events || []).filter((e) => ['goal', 'penGoal', 'penMiss', 'red', 'secondYellow', 'yellow'].includes(e.type)).map((e) => `${e.min}${e.add ? '+' + e.add : ''} ${e.type} ${e.side}`), left: !!w.scripts?.[id] } }, fx.id)
await page.evaluate((id) => window.__game.getState().go({ name: 'fixture', params: { id } }), fx.id)
await shot('edited-report', 900)
console.log(JSON.stringify({ before, after, moved, fx, script: { bias: script?.bias, score: script?.score, events: script?.events?.map((e) => `${e.min} ${e.kind} ${e.side} ${e.pen || ''}`) }, res, errors }, null, 1))
await browser.close()
